# Money Pot - Cloudflare Pages Configuration
name = "money-pot"
compatibility_date = "2025-04-24"

[assets]
directory = "dist"
not_found_handling = "single-page-application"

[observability]
enabled = true

# KV storage for 1P authentication service
[[kv_namespaces]]
binding = "KV"
id = "money-pot-kv"
preview_id = "money-pot-kv-preview"

# Environment variables for production
[vars]
NODE_ENV = "production"
APTOS_NODE_URL = "https://fullnode.testnet.aptoslabs.com/v1"
MONEY_POT_CONTRACT_ADDRESS = "0xea89ef9798a210009339ea6105c2008d8e154f8b5ae1807911c86320ea03ff3f"
VERIFIER_SERVICE_URL = "https://auth.money-pot.unreal.art"
MONEY_AUTH_URL = "https://auth.money-pot.unreal.art"
USDC_TOKEN_ADDRESS = "0xf22bede237a07e121b56d91a491eb7bcdfd1f5907926a9e58338f964a01b17da"
