# Money Pot - Cloudflare Pages Configuration
name = "money-pot"
main = "worker/index.ts"
compatibility_date = "2025-04-24"

[assets]
directory = "dist"
not_found_handling = "single-page-application"
run_worker_first = ["/api/*"]

[observability]
enabled = true

# KV storage for 1P authentication service
[[kv_namespaces]]
binding = "KV"
id = "money-pot-kv"
preview_id = "money-pot-kv-preview"

# Environment variables for production
[vars]
NODE_ENV = "production"
